pipeline{
    agent any

    stages{
        stage('Get Project'){
            steps{
                git 'https://github.com/takfarinassaber/CT5209_test1Maven.git'
            }
        }
        stage('build'){
            steps{
                sh 'mvn clean:clean'
                sh 'mvn dependency:copy-dependencies'
                sh 'mvn compiler:compile'
            }
        }
        stage('Exec'){
            steps{
                sh 'mvn exec:java'
            }
        }
    }
}